//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int ID { get; set; }
        public int AuthorID { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public string image { get; set; }
    
        public virtual Authors Authors { get; set; }
    }
}
