//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLogs
    {
        public int LogID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> SettingID { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Settings Settings { get; set; }
    }
}
